# This cfg is part of the internal variability experiment in the JAMES24 submission. See runs/cnn_lstm/mpi-esm1-2-lr/m_member_subsets_with_m50_eval_on_all_spcmp_dwp_manyr/config/config.yaml for details

device: 'cpu' # 'cpu'
seed: 42
open_data_parallel: True

repo_root: '/home/lutjens/climate-emulator/'
data_root: '/d3/lutjens/bc3/data/'
data_path: '/d3/lutjens/bc3/data/raw/CMIP6/MPI-ESM1-2-LR/' # raw data downloaded from CMIPX
data_path_interim: '/d3/lutjens/bc3/data/interim/CMIP6/MPI-ESM1-2-LR/' # interim data, such as, statistical summaries
data_path_climatebench: '/home/lutjens/climate-emulator-tutorial/data/raw/climatebench/' # climatebench data
path_experiment: '/home/lutjens/climate-emulator/runs/pattern_scaling/mpi-esm1-2-lr/m_member_subsets_with_m50_replace_False_eval_on_all_manyr/' # root path to experiment
path_sweep_cfg: '/home/lutjens/climate-emulator/runs/pattern_scaling/mpi-esm1-2-lr/m_member_subsets_with_m50_replace_False_eval_on_all_manyr/config/sweep.yaml' # Path to hyperparameter sweep config yaml. Only used if args.sweep == True
dir_m_members_subsets_csv: '/home/lutjens/climate-emulator/runs/pattern_scaling/mpi-esm1-2-lr/m_member_subsets_with_m50_replace_False_eval_on_all_manyr/config/'
filename_m_members_subsets_csv: 'm_member_subsets_with_m50_replace_False_eval_on_all_manyr.csv'
# wandb_project_name: 'emcli-mpi-esm1-2-lr-m_member_subsets_with_m50_replace_False_eval_on_all_manyr'

eval_on_all_member_mean: True
member_mode: 'ascending-repeat' # 'equal', 'ascending', 'ascending-repeat'
max_number_of_members_per_subset: 50
skip_subsets: 1
replace: False
equal_number_of_members_in_each_subset: null
number_of_subsets: null
idx_member_subset: null # Idx of member subset (with m members); if given only this subset is used for training
memberseed: 42 # Seed for creating member subsets