0:
  Y_rmse_global_np: 0.07444256616327406
  Y_rmse_spatial: 0.37237737968432183
  batch_size: 16
  best_checkpoint_path: /mnt/c/Users/Bjoern/code/climate-emulator-presubmission-tst/runs/cnn_lstm/mpi-esm1-2-lr/default//pr/checkpoints/model.e02-0.0785.keras
  best_val_loss: 0.0785
  data_path: /mnt/c/Users/Bjoern/data/climate-emulator-presubmission-tst/data/raw/CMIP6/MPI-ESM1-2-LR/
  data_path_climatebench: /mnt/c/Users/Bjoern/data/climate-emulator-presubmission-tst/data/raw/climatebench/
  data_path_interim: /mnt/c/Users/Bjoern/data/climate-emulator-presubmission-tst/data/interim/CMIP6/MPI-ESM1-2-LR/
  data_root: /mnt/c/Users/Bjoern/data/climate-emulator-presubmission-tst/data/
  data_var: pr
  device: cuda:0
  early_stopping_patience: 20
  epochs: 2
  idx_member_subset: 0
  learning_rate: 0.001
  loss_function: mse
  m_member_subset: null
  memberseed: 0
  open_data_parallel: false
  optimizer: rmsprop
  path_cfg: runs/cnn_lstm/mpi-esm1-2-lr/default/config/config.yaml
  path_checkpoints: /mnt/c/Users/Bjoern/code/climate-emulator-presubmission-tst/runs/cnn_lstm/mpi-esm1-2-lr/default//pr/checkpoints/
  path_experiment: /mnt/c/Users/Bjoern/code/climate-emulator-presubmission-tst/runs/cnn_lstm/mpi-esm1-2-lr/default/
  path_logs: /mnt/c/Users/Bjoern/code/climate-emulator-presubmission-tst/runs/cnn_lstm/mpi-esm1-2-lr/default//pr/logs/
  path_m_members_subsets_csv: /mnt/c/Users/Bjoern/code/climate-emulator-presubmission-tst/runs/cnn_lstm/mpi-esm1-2-lr/default/config/m_member_subsets.csv
  path_wandb: /mnt/c/Users/Bjoern/code/climate-emulator-presubmission-tst/runs/cnn_lstm/mpi-esm1-2-lr/default//pr
  repo_root: /mnt/c/Users/Bjoern/code/climate-emulator-presubmission-tst/
  seed: 42
  slider: 10
  task_id: 1
  use_deterministic_algorithms: true
  wandb_project_name: emcli-mpi-esm1-2-lr-default-delete
  wandb_run_id: 0dwwqikl
  wandb_run_name: avid-glitter-3
  warn_only: true
  weight_decay: null
